name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]

permissions:
  packages: write
  contents: write
  pull-requests: write

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby (installs .ruby-version, runs bundle install)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test
        run: |
          bin/rails db:setup
          bundle exec --verbose rspec
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: test
          WITH_COVERAGE: true
          DISABLE_SPRING: 1
          SLACK_OAUTH_SCOPE: ${{ secrets.SLACK_OAUTH_SCOPE }}
    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
